// <auto-generated> to shut up linter
using ArcCreate.Gameplay.Data;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "GamemodeNoteSkin", menuName = "Skin Option/NoteGamemode/Joycon")]
    public class JoyconNoteSkinOption : GamemodeNoteSkinOption
    {
        public Sprite TapSkinLeft;
        public Sprite TapSkinRight;
        public Sprite HoldSkinLeft;
        public Sprite HoldSkinRight;
        public Sprite HoldHighlightSkinLeft;
        public Sprite HoldHighlightSkinRight;
        public Sprite[] ArcCapSprites;
        public Material ArcTapSkinLeft;
        public Material ArcTapSkinMiddle;
        public Material ArcTapSkinRight;

        public override (Mesh mesh, Material material) GetArcTapSkin(ArcTap note)
        {
            if (note.Sfx != "none")
            {
                return (ArcTapSfxMesh, ArcTapSfxSkin);
            }

            if (Mathf.Abs(note.WorldX) <= Values.ArcTapMiddleWorldXRange)
            {
                return (ArcTapMesh, ArcTapSkinMiddle);
            }

            if (ArcFormula.WorldXToArc(note.WorldX) < 0.5f)
            {
                return (ArcTapMesh, ArcTapSkinLeft);
            }

            return (ArcTapMesh, ArcTapSkinRight);
        }

        public override (Sprite normal, Sprite highlight) GetHoldSkin(Hold note)
            => (note.Lane <= 2) ? (HoldSkinLeft, HoldHighlightSkinLeft) : (HoldSkinRight, HoldHighlightSkinRight);

        public override Sprite GetTapSkin(Tap note)
            => (note.Lane <= 2) ? TapSkinLeft : TapSkinRight;

        public override Sprite GetArcCapSprite(Arc arc)
        {
            if (arc.Color < 0 || arc.Color > ArcCapSprites.Length)
            {
                return ArcCapSprites[ArcCapSprites.Length - 1];
            }
            return ArcCapSprites[arc.Color];
        }
    }
}