// <auto-generated> to shut up linter
using UnityEngine;
using UnityEngine.Events;

namespace ArcCreate.SceneTransition
{
    [CreateAssetMenu(fileName = "String", menuName = "ScriptableObject/String")]
    public class StringSO : ScriptableObject
    {
        private string value;
        public string Value
        {
            get => value;
            set
            {
                this.value = value;
                OnValueChange.Invoke(value);
            }
        }

        public OnChangeEvent OnValueChange { get; set; } = new OnChangeEvent();

        public class OnChangeEvent : UnityEvent<string>
        {
        }
    }
}