// <auto-generated> to shut up linter
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Accent", menuName = "Skin Option/Accent")]
    public class AccentOption : ScriptableObject
    {
        public string Name;
        public Sprite CriticalLineSkin;
        public Sprite CriticalLineExtraSkin;
        public Color ComboColor;
    }
}