// <auto-generated> to shut up linter
using System.IO;
using ArcCreate.Utility;
using Cysharp.Threading.Tasks;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Accent", menuName = "Skin Option/Accent")]
    public class AccentOption : ScriptableObject
    {
        public string Name;
        public Sprite CriticalLineSkin;
        public Sprite CriticalLineExtraSkin;
        public Color ComboColor;

        private Sprite replacedCriticalLine;
        private Sprite replacedCriticalLineExtra;

        internal async UniTask LoadExternalSkin()
        {
            var crit = await Importer.GetSprite(Path.Combine(Values.SkinFolderPath, "CriticalLine", CriticalLineSkin.name + ".png"));
            if (crit != null)
            {
                replacedCriticalLine = CriticalLineSkin;
                CriticalLineSkin = crit;
            }

            var critExtra = await Importer.GetSprite(Path.Combine(Values.SkinFolderPath, "CriticalLine", CriticalLineExtraSkin.name + ".png"));
            if (critExtra != null)
            {
                replacedCriticalLineExtra = CriticalLineExtraSkin;
                CriticalLineExtraSkin = critExtra;
            }
        }

        internal void UnloadExternalSkin()
        {
            if (replacedCriticalLine != null)
            {
                Destroy(CriticalLineSkin);
                CriticalLineSkin = replacedCriticalLine;
                replacedCriticalLine = null;
            }

            if (replacedCriticalLineExtra != null)
            {
                Destroy(CriticalLineExtraSkin);
                CriticalLineExtraSkin = replacedCriticalLineExtra;
                replacedCriticalLineExtra = null;
            }
        }
    }
}