// <auto-generated> to shut up linter
using System.IO;
using ArcCreate.Utility;
using Cysharp.Threading.Tasks;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Alignment", menuName = "Skin Option/Alignment")]
    public class AlignmentOption : ScriptableObject
    {
        public string Name;
        public NoteSkinOption DefaultNoteOption;
        public ParticleSkinOption DefaultParticleOption;
        public TrackSkinOption DefaultTrackOption;
        public SingleLineOption DefaultSingleLineOption;
        public AccentOption DefaultAccentOption;
        public Sprite JacketShadowSkin;
        public Sprite DefaultBackground;

        private Sprite replacedJacketShadow;
        private Sprite replacedBackground;

        internal async UniTask LoadExternalSkin()
        {
            var jacketShadow = await Importer.GetSprite(Path.Combine(Values.SkinFolderPath, "JacketShadow", JacketShadowSkin.name + ".png"));
            if (jacketShadow != null)
            {
                replacedJacketShadow = JacketShadowSkin;
                JacketShadowSkin = jacketShadow;
            }

            var background = await Importer.GetSprite(Path.Combine(Values.SkinFolderPath, "Background", DefaultBackground.name + ".png"));
            if (background != null)
            {
                replacedBackground = DefaultBackground;
                DefaultBackground = background;
            }
        }

        internal void UnloadExternalSkin()
        {
            if (replacedJacketShadow != null)
            {
                Destroy(JacketShadowSkin);
                JacketShadowSkin = replacedJacketShadow;
                replacedJacketShadow = null;
            }

            if (replacedBackground != null)
            {
                Destroy(DefaultBackground);
                DefaultBackground = replacedBackground;
                replacedBackground = null;
            }
        }
    }
}