// <auto-generated> to shut up linter
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Particle", menuName = "Skin Option/Particle")]
    public class ParticleSkinOption : ScriptableObject
    {
        public string Name;
        public Texture ParticleSkin;
        public Texture SfxParticleSkin;
        public Color HoldEffectColorMin;
        public Color HoldEffectColorMax;
    }
}