// <auto-generated> to shut up linter
using System.IO;
using ArcCreate.Utility;
using Cysharp.Threading.Tasks;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Particle", menuName = "Skin Option/Particle")]
    public class ParticleSkinOption : ScriptableObject
    {
        public string Name;
        public Texture ParticleSkin;
        public Texture SfxParticleSkin;
        public Color HoldEffectColorMin;
        public Color HoldEffectColorMax;

        private Texture replacedParticle;

        private Texture replacedSfxParticle;

        internal async UniTask LoadExternalSkin()
        {
            var part = await Importer.GetTexture(Path.Combine(Values.SkinFolderPath, "Particle", ParticleSkin.name + ".png"));
            if (part != null)
            {
                replacedParticle = ParticleSkin;
                ParticleSkin = part;
            }

            var partsfx = await Importer.GetTexture(Path.Combine(Values.SkinFolderPath, "Particle", SfxParticleSkin.name + ".png"));
            if (partsfx != null)
            {
                replacedSfxParticle = SfxParticleSkin;
                SfxParticleSkin = partsfx;
            }
        }

        internal void UnloadExternalSkin()
        {
            if (replacedParticle != null)
            {
                Destroy(ParticleSkin);
                ParticleSkin = replacedParticle;
                replacedParticle = null;
            }

            if (replacedSfxParticle != null)
            {
                Destroy(SfxParticleSkin);
                SfxParticleSkin = replacedSfxParticle;
                replacedSfxParticle = null;
            }
        }
    }
}