// <auto-generated> to shut up linter
using Cysharp.Threading.Tasks;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Particle", menuName = "Skin Option/Particle")]
    public class ParticleSkinOption : ScriptableObject
    {
        public string Name;
        [SerializeField] private Texture particleSkin;
        [SerializeField] private Texture sfxParticleSkin;
        public Color HoldEffectColorMin;
        public Color HoldEffectColorMax;
        public Gradient HoldEffectFromGradient;
        public Gradient HoldEffectToGradient;

        public ExternalTexture ParticleSkin { get; private set; }

        public ExternalTexture SfxParticleSkin { get; private set; }

        internal void RegisterExternalSkin()
        {
            ParticleSkin = new ExternalTexture(particleSkin, "Particles");
            SfxParticleSkin = new ExternalTexture(sfxParticleSkin, "Particles");
        }

        internal async UniTask LoadExternalSkin()
        {
            await ParticleSkin.Load();
            await SfxParticleSkin.Load();
        }

        internal void UnloadExternalSkin()
        {
            ParticleSkin.Unload();
            SfxParticleSkin.Unload();
        }
    }
}