// <auto-generated> to shut up linter
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "SingleLine", menuName = "Skin Option/SingleLine")]
    public class SingleLineOption : ScriptableObject
    {
        public string Name;
        public bool Enable;
        public Sprite SingleLineSkin;
    }
}