// <auto-generated> to shut up linter
using System.IO;
using ArcCreate.Utility;
using Cysharp.Threading.Tasks;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "SingleLine", menuName = "Skin Option/SingleLine")]
    public class SingleLineOption : ScriptableObject
    {
        public string Name;
        public bool Enable;
        public Sprite SingleLineSkin;

        private Sprite replacedSingleLineSkin;

        internal async UniTask LoadExternalSkin()
        {
            var single = await Importer.GetSprite(Path.Combine(Values.SkinFolderPath, "Note", SingleLineSkin.name + ".png"));
            if (single != null)
            {
                replacedSingleLineSkin = SingleLineSkin;
                SingleLineSkin = single;
            }
        }

        internal void UnloadExternalSkin()
        {
            if (replacedSingleLineSkin != null)
            {
                Destroy(SingleLineSkin);
                SingleLineSkin = replacedSingleLineSkin;
                replacedSingleLineSkin = null;
            }
        }
    }
}