// <auto-generated> to shut up linter
using Cysharp.Threading.Tasks;
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Track", menuName = "Skin Option/Track")]
    public class TrackSkinOption : ScriptableObject
    {
        public string Name;
        [SerializeField] private Sprite trackSkin;
        [SerializeField] private Sprite trackExtraSkin;

        public ExternalSprite TrackSkin { get; private set; }
        public ExternalSprite TrackExtraSkin { get; private set; }

        internal void RegisterExternalSkin()
        {
            TrackSkin = new ExternalSprite(trackSkin, "Track", true);
            TrackExtraSkin = new ExternalSprite(trackExtraSkin, "Track", true);
        }

        internal async UniTask LoadExternalSkin()
        {
            await TrackSkin.Load();
            await TrackExtraSkin.Load();
        }

        internal void UnloadExternalSkin()
        {
            TrackSkin.Unload();
            TrackExtraSkin.Unload();
        }
    }
}