// <auto-generated> to shut up linter
using UnityEngine;

namespace ArcCreate.Gameplay.Skin
{
    [CreateAssetMenu(fileName = "Track", menuName = "Skin Option/Track")]
    public class TrackSkinOption : ScriptableObject
    {
        public string Name;
        public Sprite TrackSkin;
        public Sprite TrackExtraSkin;
    }
}